debug: false

# Everything related to GIT configurations
git:
  # This path should point to the binary file of git, you should set it according to your OS
  exec-path: /path/to/bin/git
  # Every command will be executed here
  working-dir: /path/to/local/repo
  # When enabled, the plugin will automatically pull the repository on startup
  pull-on-startup: false
  # Sync local and remote repos on startup
  fetch-on-startup: false
  # This can be a branch, commit hash or tag depending on your needs
  source: master
