debug: false
# Will do `git init` if there's no repository at /plugins/
create-repo-if-not-exists: false
# When enabled, the plugin will automatically pull the repository on startup
pull-on-startup: false
git:
  # This path should point to the binary file of git, you should set it according to your OS
  path: /path/to/bin/git
  # As of now the plugin only supports HTTPS authentication and you MUST provide the credentials in the URL or else the initialization will crash
  repo: https://<user>:<pass>@<host>/<repo>.git
  # You can specify the source of your changes, you can use different branches for testing purposes
  branch: master
