debug: false
git:
  path: /mnt/g/MinecraftServers/Development/PluginTesting/.craftversion/git/usr/bin/git
  repo: https://github.com/qelli/minelatino-config-pop.git
  accessKey: "poawmdpoawmdpoawmdpoawmdopa"
  branch: master

