name: CraftVersion
version: '1.0-SNAPSHOT'
main: dev.qelli.minecraft.craftversion.CraftVersion
api-version: '1.13'
authors: [ blithe_kitsune ]
website: https://qelli.dev
commands:
  craftversion:
    description: CraftVersion suite
    usage: /craftversion <action>
    permission: craftversion.admin
    aliases: [ git ]
