name: GitCraft
version: '1.0-SNAPSHOT'
main: dev.qelli.minecraft.gitcraft.GitCraft
api-version: '1.13'
authors: [ blithe_kitsune ]
website: https://qelli.dev
commands:
  gitcraft:
    description: GitCraft suite
    usage: /gitcraft <action>
    permission: gitcraft.admin
    aliases: [ git ]
